# Generated by Django 5.1.2 on 2024-10-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='')),
                ('company', models.CharField(max_length=255, verbose_name='AO')),
                ('cost', models.CharField(max_length=255, verbose_name='Цена от:')),
                ('discription', models.TextField(verbose_name='Описание:')),
                ('transmision', models.CharField(max_length=50, verbose_name='Трансмиссия:')),
                ('engineType', models.CharField(max_length=20, verbose_name='Тип двигателя:')),
                ('engineCapacity', models.CharField(max_length=20, verbose_name='Объем Двигателя:')),
                ('power', models.CharField(max_length=20, verbose_name='Мощность:')),
                ('actuator', models.CharField(max_length=20, verbose_name='Привод:')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес:')),
                ('number', models.CharField(max_length=20, verbose_name='Телефон:')),
                ('email', models.CharField(max_length=200, verbose_name='E-mail:')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
