# Generated by Django 5.1.2 on 2024-10-26 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wear_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_card',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wear_app.category', verbose_name='Выбирите категорию'),
        ),
        migrations.AlterField(
            model_name='car_card',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название Машины'),
        ),
    ]
