# Generated by Django 5.1.2 on 2024-10-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wear_app', '0002_car_card_category_alter_car_card_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/', verbose_name='Фотография'),
        ),
    ]
