# Generated by Django 5.1.2 on 2024-10-27 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wear_app', '0003_car_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_card',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации'),
        ),
    ]
