# Generated by Django 5.1.2 on 2024-10-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wear_app', '0004_car_card_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Фотография'),
        ),
    ]
