# Generated by Django 5.1.2 on 2024-10-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wear_app', '0006_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_card',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='created_at',
            new_name='date',
        ),
    ]
